### ISSUE TITLE
Why has this project not been fully open-sourced?

### ISSUE THREAD

**Issue by PragmaTwice** [alibaba/proximabilin#5]
We can see in [this directory](https://github.com/alibaba/proximabilin/tree/master/deps/proxima) that the (suspected) core part of this project, proxima, is not open source, and the directory `deps/proxima/lib` contains binary files of the library for different platforms. What is the reason for this? Is this another KPI open-source project of Alibaba?

**Comment by aboutZZ** [comment]
Yes, another KPI drived "Open source" project

**Comment by xunki** [comment]
2 years ago...
just funny...
