### ISSUE TITLE
docker镜像不存在

### ISSUE THREAD

**Issue by divenswu** [alibaba/proximabilin#7]
docker pull ghcr.io/alibaba/proxima-be

Using default tag: latest
Error response from daemon: manifest unknown

**Comment by bingdai86** [comment]
The docker repository is ghcr.io/proximabilin/proxima-be, and current version is 0.2.0.

 You can pull it by
```shell
docker pull ghcr.io/proximabilin//proxima-be:0.2.0
```

**Comment by divenswu** [comment]
thanks, perfect。
