### ISSUE TITLE
MySQL Repository 不能同步数据到ProximaBE中

### ISSUE THREAD

**Issue by divenswu** [alibaba/proximabilin#9]
前提条件:
    部署到同一机器的docker中，其中机器的IP地址为：172.16.36.229。

具体的操作步骤：
1、docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7 且修改my.cnf文件：
[mysqld]
server-id           = 12000
log_bin             = binlog
binlog_format       = ROW
运行show master logs;后能得到binlog的列表。

2、启动ProximaBE
sudo docker run -d --name proxima-bilin-engine -p 16000:16000 -p 16001:16001 \
      -v /home/root/proxima-be/conf:/var/lib/proxima-be/conf \
      -v /home/root/proxima-be/data:/var/lib/proxima-be/data \
      -v /home/root/proxima-be/log:/var/lib/proxima-be/log \
      ghcr.io/proximabilin/proxima-be:0.2.0
配置信息：
common_config {
	grpc_listen_port: 16000
	http_listen_port: 16001
	logger_type: "AppendLogger"
	log_directory: "./log/"
	log_file: "proxima_be.log"
	log_level: 1
}

query_config {
	query_thread_count: 8
}

index_config {
	max_build_qps: 0
	index_directory: "./data/"
	flush_internal: 300
}

meta_config {
	meta_uri: "sqlite:///var/lib/proxima-be/data/proxima_be_meta.sqlite"
}

3、启动MySQL Repository
sudo docker run -d --name proxima-mysql-repository  \
      -v /home/root/proxima-be/conf:/var/lib/proxima-be/conf \
      -v /home/root/proxima-be/data:/var/lib/proxima-be/data \
      -v /home/root/proxima-be/log:/var/lib/proxima-be/log \
      ghcr.io/proximabilin/proxima-be:0.2.0 \
      /var/lib/proxima-be/bin/mysql_repository --config /var/lib/proxima-be/conf/mysql_repo.conf

配置信息：
common_config {
    log_directory: "/var/lib/proxima-be/log/"
    log_file: "mysql_repo.log"
    log_level: 1
}
repository_config {
    index_agent_addr: "172.16.36.229:16000"
}

4、测试脚本使用Python中的测试脚本：mysql_example.py
运行中打印的日志中不能搜索出向量，且stats_collection接口返回：'total_doc_count': 0
```
CollectionStats{
    'collection_name': 'iris',
     'collection_path': './data//iris',
     'total_doc_count': 0,
     'total_segment_count': 1,
     'total_index_file_count': 6, 
    'total_index_file_size': 5455872, 
    'segment_stats': [SegmentStats{'segment_id': 0, 'state': <SegmentState.WRITING: 1>, 'doc_count': 0, 'index_file_count': 2, 'index_file_size': 2138112, 'min_doc_id': 0, 'max_doc_id': 0, 'min_primary_key': 18446744073709551615, 'max_primary_key': 0, 'min_timestamp': 18446744073709551615, 'max_timestamp': 0, 'min_lsn': 18446744073709551615, 'max_lsn': 0, 'segment_path': ''}]
}
```

**Comment by chendianzhang** [comment]
It seems that your mysql-repository container cannot access proxima_be container.
You can solve this problem by adding "--net=host" parameter when starting mysql-repository.
For example:
```shell
sudo docker run -d --name proxima-mysql-repository --net=host 
-v /home/root/proxima-be/conf:/var/lib/proxima-be/conf
-v /home/root/proxima-be/data:/var/lib/proxima-be/data
-v /home/root/proxima-be/log:/var/lib/proxima-be/log
ghcr.io/proximabilin/proxima-be:0.2.0
/var/lib/proxima-be/bin/mysql_repository --config /var/lib/proxima-be/conf/mysql_repo.conf
```

**Comment by divenswu** [comment]
仍然不能同步数据：
mysql-repository中只有以下日志，并没有提示启动成功的日志。
I1104 04:36:34.857808     1 collection_manager.cc:350] server_version: 0.2.0
I1104 04:36:34.858183     1 collection_manager.cc:351] mysql_repository_version: 0.2.0
I1104 04:36:34.858204     1 collection_manager.cc:259] Start Collection Manager.

备注：
mysql-repository 容器是可以正常通过16000端口访问proxima-be的grpc端口。

**Comment by chendianzhang** [comment]
Strange, it works fine for me.
When mysql-repository starts, there is an infinite loop inside. So never mind if there is a success log, as long as there is no error log it means it is working fine.
Would you please add `proxima_be.log.INFO
` and `proxima_be.log.ERROR`（if any）
 information so that I can track the problem. Thanks

**Comment by divenswu** [comment]
查看了一下源代码，发现了问题。有一个文档没有描述的隐含参数信息：
在mysql repository服务中的Repository Config中有个参数：repository_name。在程序中DatabaseRepository中的repository_name参数必须和服务中配置的参数一致。
